name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: npm

    - run: npm i -g angular-cli@latest
    - run: npm ci
    - run: ng test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
    - run: ng deploy --base-href=/ghs-editor/

