name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: npm

    - name: Setup git profile
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
    - run: npm i -g @angular/cli@latest
    - run: npm ci
    - run: ng test --no-watch --no-progress --browsers=ChromeHeadlessCI

    - name: build and publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ng deploy --base-href=/ghs-editor/ --no-silent

